theme: jekyll-theme-minimal
logo: /1.jpeg
title: 山风(独舞的蓝精灵)
description: 诗人简介: 黄真，男，七零后，陕西商洛人士,笔名“山风” ，网名“独舞的蓝精灵”，酷爱中英文创作，用笔记录生活感悟已然成习惯，被朋友圈和文学圈誉为“哲思型散文家”、“怀乡诗人”。现为现为陕西审核青年文学协会会员、《中国文学艺术联盟》的签约作者，近两年诗歌、散文二百余首（篇）散见于《中国文学艺术联盟》《绿色文学》》《延河》《天竺山杂志》《大西北诗人》《兰图多采诗社》《黄土情文学》等多家平台。在文学艺术道路上，追寻文字与心灵对话的轻灵和自由，携带对故土的眷恋和对生活的挚爱常年笔耕不辍，追求简单自然的生活方式：一周读一本书、写一篇文、骑行两次，梦想有一辆单车骑行走天涯。
